# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      # Make installs deterministic and avoid platform-specific optional deps
      - name: Configure npm for CI
        run: |
          echo "engine-strict=false" >> .npmrc
          echo "fund=false" >> .npmrc
          echo "audit=false" >> .npmrc
          echo "omit=optional" >> .npmrc

      - name: Install
        run: npm ci --omit=optional

      - name: Format (check then fix)
        run: npm run format:check || npm run format

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --coverage

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-node-${{ matrix.node }}
          path: coverage
